// ─────────────────────────────────────────────────────────────────────────
// CONFIG + static data — copied VERBATIM from the original widget.
// Source lines 1285-1923. Pure data only (no DOM, no functions).
// packageCatalog is exported as a live binding and mutated IN PLACE by
// the products loader (see api/products.js) — never reassigned.
// ─────────────────────────────────────────────────────────────────────────

    const CONFIG = {
      crmApiBase:             "https://www.zohoapis.com/crm/v8",
      crmConnectionName:      "zohocrm_connection11",
      creatorConnectionName:  "zoho_creator_connection1",
      paymentsApiBase:        "https://payments.zoho.in/api/v1",
      paymentsConnectionName: "zohopayments_connection",
      paymentsAccountId:      "",  // ← set your Zoho Payments Account ID (scrubbed for the public repo)
      paymentsApiKey:         "",  // ← set your Zoho Payments API key, Settings > Developer Space (scrubbed for the public repo)
      paymentsDomain:         "IN",         // ← 2-letter country code
      modules: {
        contacts:   "Contacts",
        deals:      "Deals",
        travellers: "Traveller_Info",
        documents:  "Document"    // ← verified via MCP: singular, NOT "Documents"
      },
      creator: {
        appOwner:        "hpatel_winnyedu",   // ← verified workspace owner
        appLinkName:     "hiren-patel",        // ← verified app link name
        portalHomePage:  "Portal_Home_page",   // ← verified portal page
        reportLinkName:  "Portal_CRM_Request_Report",
        productReportLinkName: "Products_Report",
        formLinkNames: {
          portalCrmRequest: "Portal_CRM_Request",              // ← verified form
          questionnaire:    "Visitor_Visa_Questionnaire_Sales1", // ← CONFIRMED production form (has real multi-select Applying_for_Country1, fixed traveller slots)
          cif:              "UK_CIF_1",                         // ← legacy alias, kept for back-compat
          cif1:             "UK_CIF_1",                         // ← verified via MCP
          cif2:             "UK_CIF_2",                         // ← verified via MCP, chained to CIF1
          cif3:             "UK_CIF_3" ,  
          schengen:         "Schengen_Visitor_visa",
          australia1:       "Australia_Customer_Information",
          australia2:       "Australia_Customer_Information_2",
          australia3:       "Australia_Customer_Information_3",
          australia4:       "Australia_Customer_Information_4",
          usa1:             "Us_Form_1",
          usa2:             "Us_Form_2",
          usa3:             "Us_Form_3",
          usa4:             "Us_Form_4"                        // ← verified via MCP, chained to CIF1+CIF2
        },
        // Report names used for updateRecordById (linking the CIF chain together).
        // cif1's report name is UNVERIFIED — the reports list showed two
        // candidates ("UK_Customer_Information" and "All_UK_CIF_1") and neither
        // matches the "<Form>_Report" pattern the other forms use. Picked
        // UK_Customer_Information as the more likely primary report; if the
        // final cross-link step silently fails, this is the first thing to check.
        reportLinkNames: {
          cif1: "UK_Customer_Information",
          cif2: "UK_CIF_2_Report",
          cif3: "UK_CIF_3_Report",
          schengen:         "Schengen_Customer_Information",
          australia1:       "Australia_Customer_Information_Report",
          australia2:       "Australia_Customer_Information_2_Report",
          australia3:       "Australia_Customer_Information_3_Report",
          australia4:       "Australia_Customer_Information_4_Report",
          usa1:             "Us_Form_1_Report",
          usa2:             "Us_Form_2_Report",
          usa3:             "Us_Form_3_Report",
          usa4:             "Us_Form_21_Report1"
        }
      },
      localStorageKey: "winnyApplication"
    };

    const steps = [
      { id: 1, key: "dealCompleted",         label: "Application",   title: "Your Application",       subtitle: "Your details, travellers, service selection, terms, and payment." },
      { id: 2, key: "questionnaireCompleted", label: "Questionnaire", title: "Questionnaire",           subtitle: "Applicant, family, countries, travel goals, and assessment questions." },
      { id: 3, key: "documentsUnlocked",      label: "Documents",     title: "Document Checklist",     subtitle: "Upload the documents required for your application. Unlocked alongside the CIF form." },
      { id: 4, key: "cifCompleted",           label: "CIF Form",      title: "Customer Information Form", subtitle: "Passport, address, employment, travel, finance, and declarations." },
      { id: 5, key: "reviewReady",            label: "Review",        title: "Review Application",     subtitle: "Confirm all application details before final submission." },
      { id: 6, key: "submitted",              label: "Submit",        title: "Application Submitted",  subtitle: "Submission confirmation and next steps." }
    ];

    const journeyStages = [
      "Journey Begins",
      "Payment Complete",
      "Case Questions",
      "Case File (CIF) and Document Submission",
      "Review & Confirm",
      "Submitted"
    ];

    // ── CRM Products — loaded from Zoho CRM Products module via Portal_CRM_Request ──
    // Fallback catalog used until CRM products are fetched
    let packageCatalog = [
      { id: "1323646000004173031", crmId: "1323646000004173031", name: "Schengen Only Visa Application", category: "Package", price: 12000, desc: "Dedicated Case Expert, Documentation Support, Government Form Filling, 3-Layer Quality Check, 100% Error-Free Submission.", tags: ["Schengen", "Visitor Visa"] },
      { id: "1323646000003723012", crmId: "1323646000003723012", name: "GOC Career Advancement Pathway - Stage 1", category: "Package", price: 45000, desc: "A1 German Language, Documentation Assistance, Fund Arrangement, Job Search, Motivational Letter, LinkedIn Profile.", tags: ["GOC", "Germany", "Work"] },
      { id: "1323646000001189202", crmId: "1323646000001189202", name: "Canada PR - Stage 1: Eligibility & Profile Readiness", category: "Package", price: 35000, desc: "ECA, NOC Code Identification, Language Test Training, CRS Score Roadmap.", tags: ["Canada", "PR", "Stage 1"] },
      { id: "1323646000001189203", crmId: "1323646000001189203", name: "Canada PR - Stage 2: EOI / Nomination Stage", category: "Package", price: 25000, desc: "Express Entry Profile, EOI Documentation Review, PNP Alignment.", tags: ["Canada", "PR", "Stage 2"] },
      { id: "1323646000001189200", crmId: "1323646000001189200", name: "Schengen Visa (Customized Itinerary)", category: "Package", price: 20000, desc: "Visa Submission, Flight Booking, Customized Itinerary, Travel Insurance, Hotel Booking, VFS Appointment.", tags: ["Schengen", "Tourism"] },
      { id: "1323646000001189198", crmId: "1323646000001189198", name: "Documented Countries Normal (Canada/UK/US/NZ)", category: "Package", price: 12000, desc: "Dedicated Case Expert, End-to-end Documentation, Form Filling, 3-Layer Quality Check.", tags: ["Canada", "UK", "USA", "NZ"] },
      { id: "1323646000001189199", crmId: "1323646000001189199", name: "Documented Countries Premium (Canada/UK/AUS/NZ)", category: "Package", price: 15000, desc: "Everything in Normal package + Priority Submission within 7 business days.", tags: ["Premium", "Priority"] },
      { id: "1323646000001189197", crmId: "1323646000001189197", name: "USA (B1/B2) Visitor Visa - Premium", category: "Package", price: 12000, desc: "3 Mock Interview Sessions + Priority Processing within 72 hours.", tags: ["USA", "B1/B2", "Premium"] },
      { id: "1323646000001189196", crmId: "1323646000001189196", name: "USA (B1/B2) Visitor Visa - Normal", category: "Package", price: 10000, desc: "DS-160 Form Filling, TravelDocs Creation, Interview Booking, 1 Mock Interview.", tags: ["USA", "B1/B2"] },
      { id: "1323646000003643003", crmId: "1323646000003643003", name: "USA Immigration Visa", category: "Package", price: 30000, desc: "USA immigration visa support and documentation.", tags: ["USA", "Immigration"] },
      { id: "1323646000001189217", crmId: "1323646000001189217", name: "Open Work Permit (OWP)", category: "Package", price: 45000, desc: "Open work permit application support.", tags: ["Work", "Canada"] },
      { id: "1323646000001189214", crmId: "1323646000001189214", name: "IELTS Training (Online)", category: "Add on", price: 15000, desc: "Online IELTS coaching and preparation.", tags: ["IELTS", "Coaching"] },
      { id: "1323646000001189220", crmId: "1323646000001189220", name: "Interview Preparation (5 Sessions)", category: "Add on", price: 1, desc: "5 expert mock interview preparation sessions.", tags: ["Interview", "Addon"] },
      { id: "1323646000001189216", crmId: "1323646000001189216", name: "Priority Processing (7 Business Days)", category: "Add on", price: 35000, desc: "Priority processing within 7 business days.", tags: ["Priority", "Addon"] },
      { id: "1323646000001189218", crmId: "1323646000001189218", name: "USA Priority Date Booking", category: "Add on", price: 15000, desc: "USA visa priority date booking service.", tags: ["USA", "Priority", "Addon"] }
    ];


    // ── Full country list for destination dropdown ────────────────────────────
    const COUNTRIES = [
      "Afghanistan","Albania","Algeria","Andorra","Angola","Antigua & Barbuda","Argentina",
      "Armenia","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados",
      "Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia & Herzegovina","Botswana",
      "Brazil","Brunei","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon","Canada",
      "Cape Verde","Central African Republic","Chad","Chile","China","Colombia","Comoros",
      "Congo","Costa Rica","Croatia","Cuba","Cyprus","Czech Republic","Denmark","Djibouti",
      "Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea",
      "Eritrea","Estonia","Eswatini","Ethiopia","Fiji","Finland","France","Gabon","Gambia",
      "Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau",
      "Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran","Iraq",
      "Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati",
      "Kosovo","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya",
      "Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives",
      "Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia",
      "Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia",
      "Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Korea",
      "North Macedonia","Norway","Oman","Pakistan","Palau","Palestine","Panama",
      "Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania",
      "Russia","Rwanda","Saint Kitts & Nevis","Saint Lucia","Saint Vincent & Grenadines",
      "Samoa","San Marino","Sao Tome & Principe","Saudi Arabia","Senegal","Serbia",
      "Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","Solomon Islands",
      "Somalia","South Africa","South Korea","South Sudan","Spain","Sri Lanka","Sudan",
      "Suriname","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand",
      "Timor-Leste","Togo","Tonga","Trinidad & Tobago","Tunisia","Turkey","Turkmenistan",
      "Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States",
      "Uruguay","Uzbekistan","Vanuatu","Vatican City","Venezuela","Vietnam","Yemen",
      "Zambia","Zimbabwe"
    ];
    // UK-CIF-only country list — separate from the global COUNTRIES array
    // above (which stays as-is for Deal destination / Questionnaire use).
    // This is the full 268-entry list actually configured on the real
    // UK CIF 1/2/3 Creator forms, matching their spelling ("and" not "&")
    // and including the extra territories Creator's list has that the
    // global 195-entry list doesn't.
    const UK_CIF_COUNTRIES = [
      "Åland Islands",
      "Afghanistan",
      "Akrotiri",
      "Albania",
      "Algeria",
      "American Samoa",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antarctica",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "Ashmore and Cartier Islands",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Bassas Da India",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia",
      "Bosnia and Herzegovina",
      "Botswana",
      "Bouvet Island",
      "Brazil",
      "British Indian Ocean Territory",
      "British Virgin Islands",
      "Brunei",
      "Bulgaria",
      "Burkina Faso",
      "Burma",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Cape Verde",
      "Caribbean Netherlands",
      "Cayman Islands",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Christmas Island",
      "Clipperton Island",
      "Cocos (Keeling) Islands",
      "Colombia",
      "Comoros",
      "Cook Islands",
      "Coral Sea Islands",
      "Costa Rica",
      "Cote D'Ivoire",
      "Croatia",
      "Cuba",
      "Curaçao",
      "Cyprus",
      "Czech Republic",
      "Democratic Republic of the Congo",
      "Denmark",
      "Dhekelia",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Ethiopia",
      "Europa Island",
      "Falkland Islands (Islas Malvinas)",
      "Faroe Islands",
      "Federated States of Micronesia",
      "Fiji",
      "Finland",
      "France",
      "French Guiana",
      "French Polynesia",
      "French Southern and Antarctic Lands",
      "Gabon",
      "Gaza Strip",
      "Georgia",
      "Germany",
      "Ghana",
      "Gibraltar",
      "Glorioso Islands",
      "Greece",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Guam",
      "Guatemala",
      "Guernsey",
      "Guinea",
      "Guinea-bissau",
      "Guyana",
      "Haiti",
      "Heard Island and Mcdonald Islands",
      "Holy See (Vatican City)",
      "Honduras",
      "Hong Kong",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Isle of Man",
      "Israel",
      "Italy",
      "Jamaica",
      "Jan Mayen",
      "Japan",
      "Jersey",
      "Jordan",
      "Juan De Nova Island",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Kosovo",
      "Kuwait",
      "Kyrgyzstan",
      "Laos",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macau",
      "Macedonia",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Martinique",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Mexico",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Montserrat",
      "Morocco",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nauru",
      "Navassa Island",
      "Nepal",
      "Netherlands",
      "Netherlands Antilles",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Niue",
      "Norfolk Island",
      "North Korea",
      "Northern Mariana Islands",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestine",
      "Panama",
      "Papua New Guinea",
      "Paracel Islands",
      "Paraguay",
      "Peru",
      "Philippines",
      "Pitcairn Islands",
      "Poland",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Republic of the Congo",
      "Reunion",
      "Romania",
      "Russia",
      "Rwanda",
      "Saint Barthélemy",
      "Saint Helena",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Martin",
      "Saint Pierre and Miquelon",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Sint Maarten",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Georgia and the South Sandwich Islands",
      "South Korea",
      "South Sudan",
      "Spain",
      "Spratly Islands",
      "Sri Lanka",
      "Sudan",
      "Suriname",
      "Svalbard",
      "Swaziland",
      "Sweden",
      "Switzerland",
      "Syria",
      "Taiwan",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "The Bahamas",
      "The Gambia",
      "Timor-leste",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad and Tobago",
      "Tromelin Island",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Turks and Caicos Islands",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Venezuela",
      "Vietnam",
      "Virgin Islands",
      "Wake Island",
      "Wallis and Futuna",
      "West Bank",
      "Western Sahara",
      "Yemen",
      "Zambia",
      "Zimbabwe"
    ];
    // 29-Jul-2026: Added Schengen, Australia, USA and multi-country CIF support.
     const SCHENGEN_COUNTRIES = new Set([
      "Austria","Belgium","Bulgaria","Croatia","Czech Republic","Czechia",
      "Denmark","Estonia","Finland","France","Germany","Greece","Hungary",
      "Iceland","Italy","Latvia","Liechtenstein","Lithuania","Luxembourg",
      "Malta","Netherlands","Norway","Poland","Portugal","Romania","Slovakia",
      "Slovenia","Spain","Sweden","Switzerland"
    ].map(country => country.toLowerCase()));
    ///////////////////////////////////////////////////
    const CIF_TYPE_DEFINITIONS = {
      schengen: {
        title: "Schengen CIF",
        icon: "🇪🇺",
        stages: [
          { tag:"f1", form:"Schengen_Visitor_visa", report:"Schengen_Customer_Information", title:"Schengen Visitor Visa" }
        ]
      },
      australia: {
        title: "Australia CIF",
        icon: "🇦🇺",
        stages: [
          { tag:"f1", form:"Australia_Customer_Information",   report:"Australia_Customer_Information_Report",   title:"Applicant & Travel" },
          { tag:"f2", form:"Australia_Customer_Information_2", report:"Australia_Customer_Information_2_Report", title:"Business & Additional Information" },
          { tag:"f3", form:"Australia_Customer_Information_3", report:"Australia_Customer_Information_3_Report", title:"Health, Character & Visa History" },
          { tag:"f4", form:"Australia_Customer_Information_4", report:"Australia_Customer_Information_4_Report", title:"Declarations" }
        ]
      },
      usa: {
        title: "USA CIF",
        icon: "🇺🇸",
        stages: [
          { tag:"f1", form:"Us_Form_1", report:"Us_Form_1_Report",  title:"Personal & Trip Information" },
          { tag:"f2", form:"Us_Form_2", report:"Us_Form_2_Report",  title:"Travel, Contact & Passport" },
          { tag:"f3", form:"Us_Form_3", report:"Us_Form_3_Report",  title:"Family, Work & Background" },
          { tag:"f4", form:"Us_Form_4", report:"Us_Form_21_Report1", title:"Security Declarations" }
        ]
      },
      uk: {
        title: "General / UK CIF",
        icon: "🇬🇧",
        stages: [
          { tag:"f1", form:"UK_CIF_1", report:"UK_Customer_Information", title:"UK CIF 1" },
          { tag:"f2", form:"UK_CIF_2", report:"UK_CIF_2_Report", title:"UK CIF 2" },
          { tag:"f3", form:"UK_CIF_3", report:"UK_CIF_3_Report", title:"UK CIF 3" }
        ]
      }
    };
    // ── Schengen category grouping (mirrors UK CIF's CIF_CATEGORIES pattern) ──
    // Built directly from the real Schengen_Visitor_visa Creator form's field
    // layout — each Creator section header was mapped to one of 6 themed
    // categories; fields inside Creator's auto-fragmented anonymous "Section"
    // blocks (created by conditional show/hide rules) inherit the category of
    // the last NAMED section before them, since in practice those fragments
    // are always continuations of the preceding named section's topic.
    const SCHENGEN_CATEGORIES = [
      { id:"personal_cat",   title:"Personal & Contact",              icon:"&#x1F464;" },
      { id:"passport_cat",   title:"Passport & Nationality",          icon:"&#x1F4D8;" },
      { id:"trip_cat",       title:"Trip & Sponsor Details",          icon:"&#x1F3AF;" },
      { id:"finance_cat",    title:"Employment, Ties &amp; Investments", icon:"&#x1F4BC;" },
      { id:"family_cat",     title:"Family",                          icon:"&#x1F46A;" },
      { id:"history_cat",    title:"Community Ties &amp; Travel History", icon:"&#x1F6C2;" }
    ];

    const SCHENGEN_FIELD_CATEGORY_MAP = {
      "Name__As_per_passport":"personal_cat",
      "Marital_Status":"personal_cat",
      "Do_you_live_outside_your_home_country":"personal_cat",
      "Phone_Number":"personal_cat",
      "Nationality":"personal_cat",
      "Your_current_country_of_residence":"personal_cat",
      "Your_current_residence_address":"personal_cat",
      "Your_email_id":"personal_cat",
      "Surname_at_Birth":"personal_cat",
      "Date_of_Birth":"personal_cat",
      "Place_of_Birth":"personal_cat",
      "Passport_Number":"passport_cat",
      "Date_of_passport_issue":"passport_cat",
      "Date_of_passport_expiry":"passport_cat",
      "Place_of_passport_issue":"passport_cat",
      "What_is_the_purpose_of_your_visit":"trip_cat",
      "What_is_the_function":"trip_cat",
      "Please_describe_your_visit":"trip_cat",
      "Please_share_tell_us_about_the_function_you_re_planning_to_attend":"trip_cat",
      "Please_share_details_of_convocation":"trip_cat",
      "What_is_the_business_activity":"trip_cat",
      "Please_describe_your_exact_purpose_of_visit":"trip_cat",
      "Have_you_decided_your_travel_dates":"trip_cat",
      "Please_provide_tentative_month_and_year_of_travel":"trip_cat",
      "When_will_you_depart":"trip_cat",
      "When_will_you_return":"trip_cat",
      "Have_you_booked_your_flight_tickets":"trip_cat",
      "Have_you_finalized_your_travel_itinerary_and_the_countries_you_plan_to_visit":"trip_cat",
      "Please_select_Schengen_country_you_will_arrive_first":"trip_cat",
      "Please_select_Schengen_country_you_will_stay_for_most_of_the_time":"trip_cat",
      "Have_you_booked_your_hotel_accommodation":"trip_cat",
      "Have_you_purchased_travel_insurance_for_your_trip":"trip_cat",
      "Number_of_entries_requested":"trip_cat",
      "How_will_you_be_funding_your_trip":"trip_cat",
      "Do_you_have_or_will_you_have_invitation_letter_for_your_visit":"trip_cat",
      "What_will_your_inviter_sponsor_cover_during_your_trip":"trip_cat",
      "Name_of_sponsor":"trip_cat",
      "Your_relationship_with_sponsor":"trip_cat",
      "Occupation_of_Sponsor":"trip_cat",
      "Sponsor_s_annual_income":"trip_cat",
      "What_is_your_current_occupation":"finance_cat",
      "Name_of_the_current_organisation_you_work_for":"finance_cat",
      "What_is_your_designation_position_in_the_organisation":"finance_cat",
      "Address_of_the_organisation":"finance_cat",
      "What_is_your_present_annual_salary":"finance_cat",
      "Describe_your_day_to_day_work_as_a_self_employed_person":"finance_cat",
      "What_is_your_annual_turnover_of_freelancing_work":"finance_cat",
      "How_much_amount_you_earn_annually_from_freelancing_work":"finance_cat",
      "What_type_of_business_do_you_own":"finance_cat",
      "What_is_the_name_of_your_business":"finance_cat",
      "Please_provide_address_of_your_business":"finance_cat",
      "What_is_the_annual_turnover_of_your_business":"finance_cat",
      "How_much_amount_you_earn_annually_from_business":"finance_cat",
      "Please_tell_us_more_about_your_business_Industry_products_you_sell_what_activities_you_perform_etc":"finance_cat",
      "What_was_the_name_of_organisation_where_you_get_retired":"finance_cat",
      "What_was_your_last_designation_position_in_the_oganisation_you_get_retired":"finance_cat",
      "Do_you_currently_receive_pension":"finance_cat",
      "What_is_the_monthly_pension_amount":"finance_cat",
      "What_is_the_name_of_the_institute_you_are_currently_studying_at":"finance_cat",
      "When_did_you_join_this_organisation":"finance_cat",
      "When_did_you_retire":"finance_cat",
      "What_is_name_of_program_course_grade_are_you_currently_studying":"finance_cat",
      "Address_of_institute_you_are_currently_studying":"finance_cat",
      "Please_describe_any_other_other_sources_of_income_employment_not_listed_above":"finance_cat",
      "Do_your_ITRs_from_last_two_years_reflects_your_occupation":"finance_cat",
      "What_is_your_personal_annual_income":"finance_cat",
      "Do_you_personally_own_any_fix_assets_properties":"finance_cat",
      "Please_check_the_properties_you_own":"finance_cat",
      "What_is_the_total_value_of_all_property_s_owned_by_you":"finance_cat",
      "Please_provide_which_type_of_other_assets_do_you_have":"finance_cat",
      "How_much_fund_available_in_your_saving_bank_account_s":"finance_cat",
      "Please_check_your_investments":"finance_cat",
      "Please_provide_which_type_of_other_investments_do_you_have":"finance_cat",
      "What_is_the_total_amount_of_investment_you_have_done":"finance_cat",
      "Relationship_with_you":"family_cat",
      "Name_of_family_member":"family_cat",
      "Date_of_Birth_of_family_member":"family_cat",
      "Where_do_they_live_Name_of_City_Town_Village":"family_cat",
      "Current_occupation_of_family_member":"family_cat",
      "Do_your_spouse_accompanying_you_for_this_visit":"family_cat",
      "Name_of_your_spouse_As_per_passport":"family_cat",
      "Spouse_s_date_of_birth":"family_cat",
      "Name_of_City_Town_Village_they_live":"family_cat",
      "In_which_country_they_live":"family_cat",
      "Current_occupation_of_your_spouse":"family_cat",
      "Your_spouse_s_Nationality":"family_cat",
      "Do_your_spouse_live_outside_your_home_country":"family_cat",
      "Your_spouse_s_current_country_of_residence":"family_cat",
      "Spouse_s_Phone":"family_cat",
      "Spouse_s_email_id":"family_cat",
      "Please_select_employment_source_of_income_of_your_spouse":"family_cat",
      "Name_of_the_current_organisation_your_spouse_work_for":"family_cat",
      "What_is_your_spouse_s_designation_position_in_the_organisation":"family_cat",
      "Address_of_the_organisation_your_spouse_working_for1":"family_cat",
      "What_is_your_spouse_s_present_annual_salary":"family_cat",
      "Please_describe_What_do_your_spouse_exactly_do_as_self_employed_person":"family_cat",
      "What_is_your_spouse_s_annual_turnover_of_feelancing_work":"family_cat",
      "How_much_amount_your_spouse_earn_annually_from_freelancing_work":"family_cat",
      "What_type_of_business_do_your_spouse_own":"family_cat",
      "What_is_the_name_of_your_spouse_s_business":"family_cat",
      "Please_provide_address_of_your_spouse_s_business":"family_cat",
      "What_is_the_annual_turnover_of_your_spouse_s_business":"family_cat",
      "How_much_amount_you_spouse_earn_annually_from_business":"family_cat",
      "Please_tell_us_more_about_your_spouse_s_business_Industry_products_you_sell_what_activities_you_pe":"family_cat",
      "What_was_the_name_of_organisation_where_your_spouse_get_retired":"family_cat",
      "What_was_the_last_designation_position_in_the_oganisation_your_spouse_get_retired":"family_cat",
      "When_did_your_spouse_join_this_organisation":"family_cat",
      "When_did_your_spouse_retire":"family_cat",
      "Do_your_spouse_currently_receive_pension":"family_cat",
      "What_is_the_monthly_pension_amount_your_spouse_receives":"family_cat",
      "What_is_the_name_of_the_institute_your_spouse_is_currently_studying_at":"family_cat",
      "What_is_name_of_program_course_grade_your_spouse_currently_studying":"family_cat",
      "Address_of_institute_your_spouse_is_currently_studying":"family_cat",
      "Please_describe_your_spouse_s_other_source_of_income_employment_which_is_not_listed_above":"family_cat",
      "Do_your_spouse_s_ITRs_from_last_two_years_reflects_your_occupation":"family_cat",
      "What_is_personal_income_of_your_spouse_in_a_year":"family_cat",
      "Relationship_with_you1":"family_cat",
      "Name_of_the_family_member":"family_cat",
      "Date_of_Birth_of_family_member1":"family_cat",
      "Where_do_they_live_Name_of_City_Town_Village1":"family_cat",
      "Current_occupation_of_family_member1":"family_cat",
      "Do_you_have_children":"family_cat",
      "Family_members_in_home_country":"family_cat",
      "Family_member_living_in_home_country_Spouse":"family_cat",
      "Add_details_of_child":"family_cat",
      "Name_of_child_as_per_passport":"family_cat",
      "Is_accompanying_you_during_this_visit":"family_cat",
      "Nationality1":"family_cat",
      "Do_they_live_at_your_current_residence_address":"family_cat",
      "Address_they_currently_live":"family_cat",
      "Phone_number1":"family_cat",
      "Email_Id":"family_cat",
      "Do_they_currently_reside_outside_their_country_of_nationality":"family_cat",
      "Which_country_do_they_live_currently":"family_cat",
      "Are_they_attending_any_Pre_school_School_College":"family_cat",
      "Name_of_the_institute_your_child_is_currently_attending":"family_cat",
      "Name_of_the_program_course_grade_they_are_studying":"family_cat",
      "Address_of_the_institute_they_are_attending":"family_cat",
      "Have_your_child_ever_visited_country_other_than_their_country_of_nationality":"family_cat",
      "Please_select_country_s_your_child_visited_in_past_10_years":"family_cat",
      "Have_your_child_applied_for_a_Schengen_Visa_in_the_past_5_years":"family_cat",
      "Please_provide_your_child_s_visa_number":"family_cat",
      "Have_your_child_provided_fingerprints_for_any_Schengen_Visa_previously":"family_cat",
      "When_did_your_child_submitted_fingerprints_for_Schengen_Visa":"family_cat",
      "Do_you_have_any_social_business_or_community_ties_at_your_home_country":"history_cat",
      "Have_you_ever_visited_any_country_other_than_your_country_of_nationality":"history_cat",
      "Please_select_country_s_you_have_visited_in_past_10_years":"history_cat",
      "Have_you_applied_for_a_Schengen_Visa_in_the_past_5_years":"history_cat",
      "Please_provide_your_visa_number":"history_cat",
      "Have_you_provided_fingerprints_for_any_Schengen_Visa_previously":"history_cat",
      "Visa_Sticker_No":"history_cat",
      "Date_field":"history_cat",
      "When_did_you_submitted_fingerprints_for_Schengen_Visa":"history_cat",
      "Have_your_spouse_ever_visited_country_other_than_their_country_of_nationality":"history_cat",
      "Please_select_country_s_your_spouse_visited_in_past_10_years":"history_cat",
      "Have_your_spouse_applied_for_a_Schengen_Visa_in_the_past_5_years":"history_cat",
      "Please_provide_your_spouse_s_visa_number":"history_cat",
      "When_did_your_spouse_submitted_fingerprints_for_Schengen_Visa":"history_cat",
      "Have_your_spouse_provided_fingerprints_for_any_Schengen_Visa_previously":"history_cat",
      "Additional_Other_important_information_related_to_applicant":"history_cat"
    };

    // Which instance types have category grouping available. Schengen is the
    // first; Australia and USA will be added here once their own category
    // maps are built.
    const GENERIC_CATEGORY_CONFIG = {
      schengen: { categories: SCHENGEN_CATEGORIES, fieldMap: SCHENGEN_FIELD_CATEGORY_MAP }
    };

export {
  CONFIG, steps, journeyStages, packageCatalog, COUNTRIES, UK_CIF_COUNTRIES,
  SCHENGEN_COUNTRIES, CIF_TYPE_DEFINITIONS, SCHENGEN_CATEGORIES,
  SCHENGEN_FIELD_CATEGORY_MAP, GENERIC_CATEGORY_CONFIG
};
